###
# # Get all users
GET http://localhost:3000/flight

###
# # Get a specific user
GET http://localhost:3000/flight/2

###
# # Create a new user
POST http://localhost:3000/flight
Content-Type: application/json

{
    "flightNumber": "AAL606",
    "origin": "KMIA",
    "destination": "SKBO",
    "departureDate": "2024-06-02T15:00:00Z",
    "arrivalDate": "2024-06-02T18:50:00Z",
    "capacity": "5"
}

###
# # Update a flight
PATCH http://localhost:3000/flight/2
Content-Type: application/json

{
  "destination": "SKRG"
}

###
# # Delete a user
DELETE http://localhost:3000/users/3

###
# ### User Challenges
GET http://localhost:3000/user_challenge?userId=1&_embed=challenge